ViewModels/ContactViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace AspNetMvcEFBootstrapAngular.ViewModels
{
    public class ContactViewModel
    {
        [Required, MinLength(3)]
        public string Name { get; set; }
        [EmailAddress]
        public string Email { get; set; }
        [Required]
        public string Subject { get; set; }
        [Required, MaxLength(250)]
        public string Message { get; set; }

    }
}

ViewModels/ListViewModel.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AspNetMvcEFBootstrapAngular.ViewModels
{
    public class ListViewModel
    {
        public int IdModel { get; set; }
        public string BitchNameModel { get; set; }
        public int NumberModel { get; set; }
        public string TiTDescriptionModel { get; set; }

        public IFormFile ProfilePictureModel { get; set; }
    }
}

Controllers/AppController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AspNetMvcEFBootstrapAngular.Services;
using AspNetMvcEFBootstrapAngular.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace AspNetMvcEFBootstrapAngular.Controllers
{
    public class AppController : Controller
    {
        private readonly INullMailService mailService;

        public AppController(INullMailService mailService)
        {
            this.mailService = mailService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult AngularIndex()
        {
            return View();
        }


        [HttpGet("contact")]
        public IActionResult Contact()
        {
            return View();
        }

        [HttpPost("contact")]
        public IActionResult Contact(ContactViewModel model)
        {
            if (ModelState.IsValid)
            {
                mailService.SendMessage("mymail@bs.ge", model.Subject, $"From: {model.Email}");
                ViewBag.UserMessage = "Mail Sent";
                ModelState.Clear();
            }
            else
            {

            }

            return View();
        }
    }
}

Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AspNetMvcEFBootstrapAngular.Data;
using AspNetMvcEFBootstrapAngular.Data.Entities;
using AspNetMvcEFBootstrapAngular.ViewModels;
using System.IO;
using Microsoft.AspNetCore.Hosting;

namespace AspNetMvcEFBootstrapAngular.Controllers
{
    public class ItemsController : Controller
    {
        private readonly ItemsContext _context;
        private readonly IWebHostEnvironment hostEnv;

        public ItemsController(ItemsContext context, IWebHostEnvironment hostEnv)
        {
            _context = context;
            this.hostEnv = hostEnv;
        }

        // GET: Items
        public async Task<IActionResult> Index()
        {
            return View(await _context.Items.ToListAsync());
        }

        // GET: Items/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Items
                .FirstOrDefaultAsync(m => m.Id == id);
            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }

        // GET: Items/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Items/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdModel,BitchNameModel,NumberModel,TiTDescriptionModel,ProfilePictureModel")] ListViewModel item)
        {
            if (ModelState.IsValid)
            {
                string uniqueFileName = UploadedFile(item);

                Item listItem = new Item
                {
                    BitchName = item.BitchNameModel,
                    ProfilePicture = uniqueFileName,
                     Number = item.NumberModel,
                      TiTDescription = item.TiTDescriptionModel
                };

                _context.Add(listItem);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(item);
        }

        private string UploadedFile(ListViewModel model)
        {
            string uniqueFileName = null;

            if (model.ProfilePictureModel != null)
            {
                string uploadsFolder = Path.Combine(hostEnv.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + model.ProfilePictureModel.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    model.ProfilePictureModel.CopyTo(fileStream);
                }
            }
            return uniqueFileName;
        }

        // GET: Items/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Items.FindAsync(id);
            if (item == null)
            {
                return NotFound();
            }
            return View(item);
        }

        // POST: Items/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdModel,BitchNameModel,NumberModel,TiTDescriptionModel,ProfilePictureModel")] ListViewModel item)
        {
            if (id != item.IdModel)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(item);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ItemExists(item.IdModel))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(item);
        }

        // GET: Items/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Items
                .FirstOrDefaultAsync(m => m.Id == id);
            if (item == null)
            {
                return NotFound();
            }

            return View(item);
        }

        // POST: Items/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var item = await _context.Items.FindAsync(id);
            _context.Items.Remove(item);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ItemExists(int id)
        {
            return _context.Items.Any(e => e.Id == id);
        }
    }
}

Views/App/AngularIndex.cshtml
@{
    ViewData["Title"] = "AngularIndex";
}
@section Scripts{

    <script src="~/clientapp/runtime-es2015.js"></script>
    <script src="~/clientapp/polyfills-es2015.js"></script>
    <script src="~/clientapp/styles-es2015.js"></script>
    <script src="~/clientapp/vendor-es2015.js"></script>
    <script src="~/clientapp/main-es2015.js"></script>

}

<h1>AngularIndex Razor</h1>

<app-root></app-root>

Views/App/Contact.cshtml
@model ContactViewModel
@{
    ViewData["Title"] = "Contact";
}

<h1 class="text-center">კონტაქტი</h1>

<div class="row">
    <div class="col-md-6">
        <div class="card card-body">
            <img src="~/images/bddbb3b5-24e7-48af-8250-b356d3127662_SK-A-3138.jpg" height="700" />
        </div>
    </div>
    <div class="col-md-6">

        

        <div class="card card-body bg-light">
            <form method="post">
                <div asp-validation-summary="All" class="text-warning"></div>
                <div class="form-group">
                    <label asp-for="Name">თქვენი სახელი:</label>
                    <input asp-for="Name" class="form-control" />
                </div>

                <div class="form-group">
                    <label asp-for="Email">თქვენი მეილი:</label>

                    <input type="email" asp-for="Email" class="form-control" />
                </div>

                <div class="form-group">
                    <label asp-for="Subject">თემა:</label>
                    <input type="text" asp-for="Subject" class="form-control" />
                </div>

                <div class="form-group">
                    <label asp-for="Message">ტექსტი:</label>
                    <textarea asp-for="Message" rows="4" class="form-control"></textarea>
                </div>

                <div class="form-group">
                    <button type="submit" value="გაგზავნა" class="btn btn-primary">გაგზავნა</button>
                    <div>@ViewBag.UserMessage</div>
                </div>
            </form>
        </div>

    </div>
</div>

Views/App/Index.cshtml
@model IEnumerable<AspNetMvcEFBootstrapAngular.Data.Entities.Item>
@{
    ViewData["Title"] = "Index";
}

    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img class="d-block w-100" src="~/carouselImages/6b5176e78625b367bbce41917c73cb27.jpg" alt="First slide">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="~/carouselImages/pics14.jpg" alt="Second slide">
            </div>
            <div class="carousel-item">
                <img class="d-block w-100" src="~/carouselImages/SK-A-3262.jpg" alt="Third slide">
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>

Views/Items/Create.cshtml
@model AspNetMvcEFBootstrapAngular.ViewModels.ListViewModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Item</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form enctype="multipart/form-data" asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="BitchNameModel" class="control-label"></label>
                <input asp-for="BitchNameModel" class="form-control" />
                <span asp-validation-for="BitchNameModel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberModel" class="control-label"></label>
                <input asp-for="NumberModel" class="form-control" />
                <span asp-validation-for="NumberModel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TiTDescriptionModel" class="control-label"></label>
                <input asp-for="TiTDescriptionModel" class="form-control" />
                <span asp-validation-for="TiTDescriptionModel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProfilePictureModel" class="control-label"></label>
                <div class="custom-file">
                    <input asp-for="ProfilePictureModel" class="custom-file-input" id="customFile">
                    <label class="custom-file-label" for="customFile">Choose file</label>
                </div>
                <span asp-validation-for="ProfilePictureModel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section scripts{
    <script type="text/javascript">

        // Add the following code if you want the name of the file appear on select
        $(".custom-file-input").on("change", function () {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
        });
    </script>
} 

Views/Items/Delete.cshtml
@model AspNetMvcEFBootstrapAngular.Data.Entities.Item

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Item</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BitchName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BitchName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Number)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Number)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TiTDescription)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TiTDescription)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProfilePicture)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProfilePicture)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Items/Details.cshtml
@model AspNetMvcEFBootstrapAngular.Data.Entities.Item

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Item</h4>
    <hr />
    <div>
        <img src="~/images/@Model.ProfilePicture" width="400" height="600" />
    </div>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BitchName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BitchName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Number)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Number)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.TiTDescription)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.TiTDescription)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ProfilePicture)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ProfilePicture)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Items/Edit.cshtml
@model AspNetMvcEFBootstrapAngular.ViewModels.ListViewModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Item</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdModel" />
            <div class="form-group">
                <label asp-for="BitchNameModel" class="control-label"></label>
                <input asp-for="BitchNameModel" class="form-control" />
                <span asp-validation-for="BitchNameModel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberModel" class="control-label"></label>
                <input asp-for="NumberModel" class="form-control" />
                <span asp-validation-for="NumberModel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TiTDescriptionModel" class="control-label"></label>
                <input asp-for="TiTDescriptionModel" class="form-control" />
                <span asp-validation-for="TiTDescriptionModel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProfilePictureModel" class="control-label"></label>
                <input asp-for="ProfilePictureModel" class="form-control" />
                <span asp-validation-for="ProfilePictureModel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Items/Index.cshtml
@model IEnumerable<AspNetMvcEFBootstrapAngular.Data.Entities.Item>

@{
    ViewData["Title"] = "Index";
}

<h1>ნაშების სია</h1>

<p>
    <a class="btn btn-primary" asp-action="Create">ახლის დამატება</a>
</p>


<div class="row">

    @foreach (var item in Model)
    {
    <div class="col-md-4">
        <div class="card text-center">
            <div>
                <span><b>სახელი: </b></span>
                @Html.DisplayFor(modelItem => item.BitchName)
            </div>
            <div>
                <span><b>ტელ. ნომერი: </b></span>
                @Html.DisplayFor(modelItem => item.Number)
            </div>
            <div>
                <span><b>ძუძუები: </b></span>
                @Html.DisplayFor(modelItem => item.TiTDescription)
            </div>
            <div>
                <img src="~/images/@item.ProfilePicture" width="200" height="300" />
            </div>
            <div>
                <div>
                    <a class="btn btn-sm btn-warning" asp-action="Edit" asp-route-id="@item.Id">ცვლილება</a> |
                    <a class="btn btn-sm btn-info" asp-action="Details" asp-route-id="@item.Id">დეტალურად</a> |
                    <a class="btn btn-sm btn-danger" asp-action="Delete" asp-route-id="@item.Id">წაშლა</a>
                </div>
            </div>
        </div>
    </div>
            }

      


    </div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>ონლაინ ბოზები</title>
    <link href="\node_modules\bootstrap\dist\css\bootstrap.min.css" rel="stylesheet" />
    <link href="D:\Users\user\source\repos\AspNetMvcEFBootstrapAngular\node_modules\font-awesome\css\font-awesome.css" rel="stylesheet" />
    <link href="../css/site.css" rel="stylesheet" />
    <base href="~/" />
</head>
<body>
    <div class="container-fluid">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a asp-controller="App" asp-action="Index" class="navbar-brand">მთავარი გვერდი</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a asp-controller="App" asp-action="Index" class="nav-link">მთავარი <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a asp-controller="Items" asp-action="Index" class="nav-link">სია</a>
                    </li>
                    <li class="nav-item">
                        <a asp-controller="App" asp-action="AngularIndex" class="nav-link">Angular</a>
                    </li>
                    <li class="nav-item">
                        <a asp-controller="App" asp-action="Contact" class="nav-link">კონტაქტი</a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>

    <div class="container">
        @RenderBody()

    </div>

    <footer>Copyright 2020 ბოზები</footer>
    <script src="/node_modules/jquery/dist/jquery.min.js"></script>
    <script src="\node_modules\bootstrap\dist\js\bootstrap.bundle.min.js"></script>
    <script src="../js/index.js"></script>
    @RenderSection("scripts", false)
</body>
</html>